"""Shared seed data for agent registry stores."""

from __future__ import annotations

from aegisai.domain.models import RegisteredAgent


def seed_agents() -> tuple[RegisteredAgent, ...]:
    return (
        RegisteredAgent(
            agent_id="agent-intake-triage",
            name="Intake & Triage Agent",
            owner="AI Platform",
            business_domain="Customer Operations",
            risk_tier="medium",
            autonomy_level=2,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory",),
            data_classes=("public", "internal", "confidential"),
            last_run_at="2026-05-25T09:10:00-07:00",
            monthly_cost_usd=42.0,
            open_incidents=0,
            value_metric="Classifies requests in under 2 seconds",
        ),
        RegisteredAgent(
            agent_id="agent-refund",
            name="Refund Agent",
            owner="Finance Operations",
            business_domain="Payments",
            risk_tier="high",
            autonomy_level=3,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "payments.issue_refund"),
            data_classes=("internal", "confidential"),
            last_run_at="2026-05-25T09:08:00-07:00",
            monthly_cost_usd=118.0,
            open_incidents=0,
            value_metric="Reduces refund review cycle time by 38%",
        ),
        RegisteredAgent(
            agent_id="agent-data-ops",
            name="Data Operations Agent",
            owner="Privacy Office",
            business_domain="Privacy Operations",
            risk_tier="critical",
            autonomy_level=2,
            status="restricted",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "privacy.modify_or_delete_data"),
            data_classes=("confidential", "restricted"),
            last_run_at="2026-05-25T08:52:00-07:00",
            monthly_cost_usd=74.0,
            open_incidents=0,
            value_metric="Prevents irreversible data actions without compliance approval",
        ),
        RegisteredAgent(
            agent_id="agent-it-ops",
            name="IT Operations Agent",
            owner="SRE",
            business_domain="Infrastructure",
            risk_tier="high",
            autonomy_level=2,
            status="pilot",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "infra.change_production_configuration"),
            data_classes=("internal", "confidential"),
            last_run_at="2026-05-25T08:34:00-07:00",
            monthly_cost_usd=96.0,
            open_incidents=1,
            value_metric="Drafts safe change plans with rollback metadata",
        ),
        RegisteredAgent(
            agent_id="agent-requirements-analyst",
            name="Requirements Analyst",
            owner="Website Build Pipeline",
            business_domain="Software Delivery",
            risk_tier="low",
            autonomy_level=2,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory",),
            data_classes=("internal",),
            last_run_at="not_run_yet",
            monthly_cost_usd=28.0,
            open_incidents=0,
            value_metric="Parses build requirements into acceptance criteria",
            budget_usd=10.0,
        ),
        RegisteredAgent(
            agent_id="agent-ui-design-analyst",
            name="UI Design Analyst",
            owner="Website Build Pipeline",
            business_domain="Software Delivery",
            risk_tier="low",
            autonomy_level=2,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "design.analyze_figma"),
            data_classes=("internal",),
            last_run_at="not_run_yet",
            monthly_cost_usd=32.0,
            open_incidents=0,
            value_metric="Produces design specs without writing code",
            budget_usd=15.0,
        ),
        RegisteredAgent(
            agent_id="agent-fe-builder",
            name="Frontend Engineer",
            owner="Website Build Pipeline",
            business_domain="Software Delivery",
            risk_tier="medium",
            autonomy_level=3,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "deploy.vercel_release"),
            data_classes=("internal",),
            last_run_at="not_run_yet",
            monthly_cost_usd=54.0,
            open_incidents=0,
            value_metric="Implements UI via gateway-governed deploy tools",
            budget_usd=20.0,
        ),
        RegisteredAgent(
            agent_id="agent-be-builder",
            name="Backend Engineer",
            owner="Website Build Pipeline",
            business_domain="Software Delivery",
            risk_tier="medium",
            autonomy_level=3,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=("rag.search_policy_memory", "deploy.render_release"),
            data_classes=("internal", "confidential"),
            last_run_at="not_run_yet",
            monthly_cost_usd=58.0,
            open_incidents=0,
            value_metric="Implements APIs with policy-bound side effects",
            budget_usd=20.0,
        ),
        RegisteredAgent(
            agent_id="agent-review-deploy",
            name="Review & Deploy Agent",
            owner="Website Build Pipeline",
            business_domain="Software Delivery",
            risk_tier="high",
            autonomy_level=2,
            status="approved",
            model_provider="OpenAI/local fallback",
            allowed_tools=(
                "rag.search_policy_memory",
                "deploy.vercel_release",
                "deploy.render_release",
            ),
            data_classes=("internal", "confidential"),
            last_run_at="not_run_yet",
            monthly_cost_usd=44.0,
            open_incidents=0,
            value_metric="Code review gate before staging/production deploy",
            budget_usd=15.0,
        ),
        RegisteredAgent(
            agent_id="venkat-ai-platform",
            name="Venkat AI Platform (VAP)",
            owner="AI Platform",
            business_domain="Multi-Agent Orchestration",
            risk_tier="medium",
            autonomy_level=3,
            status="pilot",
            model_provider="OpenRouter",
            allowed_tools=(
                "rag.search_policy_memory",
                "notify.slack",
                "notify.telegram",
                "notify.whatsapp",
            ),
            data_classes=("internal", "confidential"),
            last_run_at="not_run_yet",
            monthly_cost_usd=62.0,
            open_incidents=0,
            value_metric="Chief orchestration with gateway-governed delivery channels",
        ),
        RegisteredAgent(
            agent_id="enterprise-rag-platform",
            name="Enterprise RAG Platform",
            owner="Knowledge Engineering",
            business_domain="Governed Retrieval",
            risk_tier="medium",
            autonomy_level=2,
            status="pilot",
            model_provider="Extractive/local",
            allowed_tools=(
                "rag.search_policy_memory",
                "rag.ingest_document",
                "rag.high_risk_answer",
            ),
            data_classes=("internal", "confidential", "restricted"),
            last_run_at="not_run_yet",
            monthly_cost_usd=28.0,
            open_incidents=0,
            value_metric="Access-aware retrieval with HITL on ingest and destructive queries",
        ),
        RegisteredAgent(
            agent_id="aegisloop-agentops",
            name="AegisLoop AgentOps Workbench",
            owner="AgentOps",
            business_domain="Mission Fleets",
            risk_tier="medium",
            autonomy_level=2,
            status="pilot",
            model_provider="OpenRouter/Ollama/local",
            allowed_tools=("mission.ship_artifact",),
            data_classes=("internal",),
            last_run_at="not_run_yet",
            monthly_cost_usd=18.0,
            open_incidents=0,
            value_metric="Mission eval gates with human-gated ship path",
        ),
        RegisteredAgent(
            agent_id="ai-content-factory",
            name="AI Content Factory",
            owner="Content Platform",
            business_domain="Content Automation",
            risk_tier="medium",
            autonomy_level=2,
            status="pilot",
            model_provider="OpenRouter/Gemini",
            allowed_tools=(
                "rag.search_policy_memory",
                "publish.linkedin",
                "publish.x",
                "publish.medium",
                "publish.substack",
                "publish.instagram",
            ),
            data_classes=("public", "internal"),
            last_run_at="not_run_yet",
            monthly_cost_usd=48.0,
            open_incidents=0,
            value_metric="Governed multi-platform content pipeline with HITL publish",
        ),
    )
