#!/usr/bin/env bash
# Capture AWS AegisAI receipt evidence. Does NOT apply or destroy infrastructure.
# Run from deploy/terraform/aws after a successful apply (or ECR-only minimal path).
# Usage: ./scripts/capture_receipt.sh
set -euo pipefail
TF_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$TF_DIR"
DAY="$(date -u +%Y%m%d)"
# Prefer architecture-portfolio artifacts if sibling checkout exists
PORTFOLIO="${ARCHITECTURE_PORTFOLIO:-$HOME/ai-architecture-portfolio}"
OUT_DIR="${AWS_RECEIPT_DIR:-$PORTFOLIO/docs/artifacts/aws-receipts}"
mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/${DAY}-aws-receipt.md"

{
  echo "# AWS AegisAI receipt — ${DAY}"
  echo
  echo "Generated by \`deploy/terraform/aws/scripts/capture_receipt.sh\` (no apply/destroy)."
  echo
  echo "## Terraform outputs (redact account ids before public commit)"
  echo
  echo '```'
  terraform output -json 2>/dev/null | python3 - <<'PY' || echo "(terraform output failed — run from applied workspace)"
import json,sys,re
try:
  data=json.load(sys.stdin)
except Exception as e:
  print(f"parse_error: {e}")
  sys.exit(0)
def scrub(s: str) -> str:
  return re.sub(r"\d{12}", "************", s)
for k,v in data.items():
  val=v.get("value")
  print(f"{k}: {scrub(json.dumps(val) if not isinstance(val,str) else val)}")
PY
  echo '```'
  echo
  echo "## Health (if alb_url present)"
  echo
  ALB="$(terraform output -raw alb_url 2>/dev/null || true)"
  if [[ -n "$ALB" ]]; then
    echo "URL host captured; body:"
    echo '```'
    curl -sS --max-time 60 "${ALB%/}/health" | head -c 800 || echo "(curl failed)"
    echo
    echo '```'
  else
    echo "_No alb_url — ECR-only minimal path is OK; note image digest below._"
  fi
  echo
  echo "## ECR image (optional)"
  echo
  REPO="$(terraform output -raw ecr_repository_url 2>/dev/null || true)"
  if [[ -n "$REPO" ]]; then
    echo "- repository URL present (redact account id before public commit)"
    echo "- digest: run \`aws ecr describe-images\` and paste image digest here"
  else
    echo "_No ecr_repository_url in this state._"
  fi
  echo
  echo "## Teardown checklist"
  echo
  echo "- [ ] \`terraform destroy\` completed same day (or ECS desired=0 + RDS stopped)"
  echo "- [ ] Budget alarm confirmed no overnight ALB burn"
  echo "- [ ] No secrets committed"
} >"$OUT"

echo "Wrote $OUT"
echo "See ai-architecture-portfolio/docs/P2_AWS_RECEIPT_RUNBOOK.md"
